name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.91425
typography_spectrum: 0.83759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffffd'
    - '#888574'
    - '#364653'
    - '#67241e'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
