name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.13594
typography_spectrum: 0.83759
title: Meet our Staff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4d4d2'
    - '#2c2723'
    - '#91a07f'
    - '#463e3b'
    - '#5b6d53'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
