name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.3246
typography_spectrum: 0.83759
title: Carlisle Bowenwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a5e77'
    - '#182327'
    - '#c6c7c2'
    - '#82878b'
    - '#fef475'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
