name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.3246
typography_spectrum: 0.83759
title: Carlisle Bowenwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#766e6c'
    - '#aaba93'
    - '#0b0c07'
    - '#fefefc'
    - '#dad7c9'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
