name: carlislebowenwork.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.83759
title: Carlisle Bowenwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#959595'
    - '#008e3f'
    - '#8cc43f'
    - '#35ab4a'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
