typography_spectrum: 0.83759
color:
  brandColors:
    - '#d4d4d2'
    - '#2c2723'
    - '#91a07f'
    - '#463e3b'
    - '#5b6d53'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50642
analytics:
  google: null
  facebook: null
  twitter: null
name: carlislebowenwork.com
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Carlisle Bowenwork
description: Center for Wholistic Health and Wellness
purpose: []
