name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.87914
typography_spectrum: 0.83759
title: Carlisle Bowenwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0805'
    - '#29361a'
    - '#c49b1b'
    - '#6e223e'
    - '#b9a8b2'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
