name: carlislebowenwork.com
favicon: null
layout_spectrum: 0.3246
typography_spectrum: 0.83759
title: Carlisle Bowenwork
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2e5305'
    - '#94b907'
    - '#669700'
    - '#27aa5c'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
