typography_spectrum: 0.83759
color:
  brandColors:
    - '#d4d4d2'
    - '#2c2723'
    - '#91a07f'
    - '#463e3b'
    - '#5b6d53'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 1
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0e7dce6-48fa-40f8-a4fc-4158b833c42a.jpg
  type: null
  appId: Carlisle Bowenwork
layout_spectrum: 0.50642
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nancy
  email: nbittinger@comcast.net
  url: carlislebowenworkpa.com
name: carlislebowenworkpa.com
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Meet the owner
    id: b42b02eb-8456-41df-9df0-e4a86717c53b
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4b6ab32-1685-4a57-9a82-e694feaa9de2.jpg
title: Center for Wholistic Health and Wellness
description: Center for Wholistic Health and Wellness
purpose: []
