typography_spectrum: 0.511867409106344
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.299201556481421
  lightness: 0.7431828991975635
  saturation: 0.6054813389200717
  rhythmicContrast: 0.8060237525496632
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/a0e7dce6-48fa-40f8-a4fc-4158b833c42a.jpg
  type: null
  appId: Carlisle Bowenwork
layout_spectrum: 0.4249839575495571
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: nbittinger@comcast.net
  url: carlislebowenworkpa.com
name: carlislebowenworkpa.com
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4b6ab32-1685-4a57-9a82-e694feaa9de2.jpg
title: Carlisle Bowenwork
description: Center for Wholistic Health and Wellness
purpose: []
